#!/usr/bin/env node
/* ============================================================================
   pack-shots.mjs — GENERATES src/shots.js

   The real product screenshots, conditioned for the film and inlined as data
   URIs so the delivered HTML stays a single self-contained file.

   Phone-screen shots are scaled to COVER the 3D phone's screen aspect (0.476)
   and centre-cropped, so they fill the device with no letterbox. The wide
   shots keep their own framing.
   ========================================================================== */
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, mkdtempSync, rmSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { tmpdir } from 'node:os';

const here = dirname(fileURLToPath(import.meta.url));
const SRC = join(here, 'shots');
const OUT = join(here, '..', 'src', 'shots.js');
const tmp = mkdtempSync(join(tmpdir(), 'shots-'));

/* key, file, how to fit, output box, jpeg quality (2 = best, 31 = worst),
   and `trim`: pixels to cut off the bottom of the source first. Two of the
   captures were taken in a browser, so their Safari toolbar is trimmed away —
   the film is showing the app, not a web page. */
const PLAN = [
  ['appHome',    'app-home.jpg',   'phone', [620, 1302], 5, 235],
  ['dailyPlay',  'daily-play.jpg', 'phone', [620, 1302], 5, 0],
  ['tradePlan',  'trade-plan.jpg', 'phone', [620, 1302], 5, 0],
  ['homescreen', 'homescreen.jpg', 'wide',  [1120, 331], 4, 0],
  ['result',     'result.jpg',     'wide',  [880, 684],  4, 0],
];

const out = {};
let total = 0;
for (const [key, file, fit, [w, h], q, trim] of PLAN) {
  const dst = join(tmp, `${key}.jpg`);
  const pre = trim ? `crop=iw:ih-${trim}:0:0,` : '';
  const vf = pre + (fit === 'phone'
    ? `scale=-1:${h}:flags=lanczos,crop=${w}:${h}`   /* cover, centre-crop */
    : `scale=${w}:${h}:flags=lanczos`);
  execFileSync('ffmpeg', ['-y', '-loglevel', 'error', '-i', join(SRC, file),
    '-vf', vf, '-q:v', String(q), dst]);
  const b64 = readFileSync(dst).toString('base64');
  out[key] = { w, h, src: `data:image/jpeg;base64,${b64}` };
  total += b64.length;
  console.log(`  ${key.padEnd(11)} ${String(w).padStart(4)}x${h}  ${(b64.length / 1024).toFixed(0)} KB`);
}
rmSync(tmp, { recursive: true, force: true });

const js = `/* ============================================================================
   shots.js — GENERATED by tools/pack-shots.mjs from tools/shots/*.jpg.
   Do not hand-edit; re-run the packer if the screenshots change.

   Real screenshots of the shipped product, inlined so the delivered HTML stays
   one self-contained file with no network requests. Phone shots are pre-cropped
   to the 3D phone's screen aspect, so they map on with no letterboxing.
   ========================================================================== */
const SHOTS = ${JSON.stringify(out)};
`;
writeFileSync(OUT, js);
console.log(`\nwrote src/shots.js · ${(js.length / 1024).toFixed(0)} KB (${(total / 1024).toFixed(0)} KB of image data)`);
